services:
  plandex-postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./scripts/init-db:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plandex-network
  plandex-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - planex_data:${PLANDEX_BASE_DIR}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@plandex-postgres:5432/${POSTGRES_DATABASE}?sslmode=disable"
      GOENV: $GOENV
      PLANDEX_BASE_DIR: $PLANDEX_BASE_DIR

    networks:
      - plandex-network
    depends_on:
      - plandex-postgres
    command:
      [
        "/bin/sh",
        "-c",
        "/scripts/wait-for-it.sh plandex-postgres:5432 -- ./plandex-server"
      ]

volumes:
  pg_data: null
  planex_data: null

networks:
  plandex-network: null
